# settings.yml
# This file defines critical settings for our Sinatra app.

# The required version of Ruby all apps must use.
required_ruby_version: "3.2.2"

# A list of gems that are not allowed in any project.
disallowed_gems:
  - "pry-byebug"
